export const paliaFishImages: Record<string, any> = {
  "Albino Eel": require("../assets/palia/fish/albino-eel.png"),
  "Alligator Gar": require("../assets/palia/fish/alligator-gar.png"),
  "Ancient Cloudminnow": require("../assets/palia/fish/ancient-cloudminnow.png"),
  "Ancient Fish": require("../assets/palia/fish/ancient-fish.png"),
  "Ancient Koi": require("../assets/palia/fish/ancient-koi.png"),
  "Angelfish": require("../assets/palia/fish/angelfish.png"),
  "Bahari Bass": require("../assets/palia/fish/bahari-bass.png"),
  "Bahari Bream": require("../assets/palia/fish/bahari-bream.png"),
  "Bahari Pike": require("../assets/palia/fish/bahari-pike.png"),
  "Barracuda": require("../assets/palia/fish/barracuda.png"),
  "Bat Ray": require("../assets/palia/fish/bat-ray.png"),
  "Beluga Sturgeon": require("../assets/palia/fish/beluga-sturgeon.png"),
  "Black Sea Bass": require("../assets/palia/fish/black-sea-bass.png"),
  "Blobfish": require("../assets/palia/fish/blobfish.png"),
  "Blue Marlin": require("../assets/palia/fish/blue-marlin.png"),
  "Blue Spotted Ray": require("../assets/palia/fish/blue-spotted-ray.png"),
  "Bluefin Tuna": require("../assets/palia/fish/bluefin-tuna.png"),
  "Bronze Bluegill": require("../assets/palia/fish/bronze-bluegill.png"),
  "Cactus Moray": require("../assets/palia/fish/cactus-moray.png"),
  "Calico Koi": require("../assets/palia/fish/calico-koi.png"),
  "Cantankerous Koi": require("../assets/palia/fish/cantankerous-koi.png"),
  "Channel Catfish": require("../assets/palia/fish/channel-catfish.png"),
  "Charged Cardinal": require("../assets/palia/fish/charged-cardinal.png"),
  "Chub": require("../assets/palia/fish/chub.png"),
  "Cloudfish": require("../assets/palia/fish/cloudfish.png"),
  "Copper Sturgeon": require("../assets/palia/fish/copper-sturgeon.png"),
  "Crimson Fangtooth": require("../assets/palia/fish/crimson-fangtooth.png"),
  "Crucian Carp": require("../assets/palia/fish/crucian-carp.png"),
  "Cutthroat Trout": require("../assets/palia/fish/cutthroat-trout.png"),
  "Dawnray": require("../assets/palia/fish/dawnray.png"),
  "Devilfish": require("../assets/palia/fish/devilfish.png"),
  "Duskray": require("../assets/palia/fish/duskray.png"),
  "Eleroo Eel": require("../assets/palia/fish/eleroo-eel.png"),
  "Enchanted Pupfish": require("../assets/palia/fish/enchanted-pupfish.png"),
  "Energized Piranha": require("../assets/palia/fish/energized-piranha.png"),
  "Enfield Eel": require("../assets/palia/fish/enfield-eel.png"),
  "Eyeless Minnow": require("../assets/palia/fish/eyeless-minnow.png"),
  "Fairy Carp": require("../assets/palia/fish/fairy-carp.png"),
  "Fathead Minnow": require("../assets/palia/fish/fathead-minnow.png"),
  "Flametongue Ray": require("../assets/palia/fish/flametongue-ray.png"),
  "Freshwater Eel": require("../assets/palia/fish/freshwater-eel.png"),
  "Giant Goldfish": require("../assets/palia/fish/giant-goldfish.png"),
  "Giant Kilima Stingray": require("../assets/palia/fish/giant-kilima-stingray.png"),
  "Gillyfin": require("../assets/palia/fish/gillyfin.png"),
  "Golden Salmon": require("../assets/palia/fish/golden-salmon.png"),
  "Green Anchovy": require("../assets/palia/fish/green-anchovy.png"),
  "Heather Manta": require("../assets/palia/fish/heather-manta.png"),
  "Highland Swiftscale": require("../assets/palia/fish/highland-swiftscale.png"),
  "Honey Loach": require("../assets/palia/fish/honey-loach.png"),
  "Hypnotic Moray": require("../assets/palia/fish/hypnotic-moray.png"),
  "Indigo Lamprey": require("../assets/palia/fish/indigo-lamprey.png"),
  "Inyrevn Mermaid": require("../assets/palia/fish/inyrevn-mermaid.png"),
  "Jade Koi": require("../assets/palia/fish/jade-koi.png"),
  "Kenli's Carp": require("../assets/palia/fish/kenlis-carp.png"),
  "Kilima Catfish": require("../assets/palia/fish/kilima-catfish.png"),
  "Kilima Grayling": require("../assets/palia/fish/kilima-grayling.png"),
  "Kilima Redfin": require("../assets/palia/fish/kilima-redfin.png"),
  "Lake Shark": require("../assets/palia/fish/lake-shark.png"),
  "Largemouth Bass": require("../assets/palia/fish/largemouth-bass.png"),
  "Long Nosed Unicorn Fish": require("../assets/palia/fish/long-nosed-unicorn-fish.png"),
  "Majiri-of-War": require("../assets/palia/fish/majiri-of-war.png"),
  "Major Manta": require("../assets/palia/fish/major-manta.png"),
  "Maws": require("../assets/palia/fish/maws.png"),
  "Midnight Floatfish": require("../assets/palia/fish/midnight-floatfish.png"),
  "Midnight Paddlefish": require("../assets/palia/fish/midnight-paddlefish.png"),
  "Mini Mullet": require("../assets/palia/fish/mini-mullet.png"),
  "Mirror Carp": require("../assets/palia/fish/mirror-carp.png"),
  "Mossyfin": require("../assets/palia/fish/mossyfin.png"),
  "Mottled Gobi": require("../assets/palia/fish/mottled-gobi.png"),
  "Mudminnow": require("../assets/palia/fish/mudminnow.png"),
  "Mutated Angler": require("../assets/palia/fish/mutated-angler.png"),
  "Oily Anchovy": require("../assets/palia/fish/oily-anchovy.png"),
  "Ooh Barracuda": require("../assets/palia/fish/ooh-barracuda.png"),
  "Orange Bluegill": require("../assets/palia/fish/orange-bluegill.png"),
  "Paddlefish": require("../assets/palia/fish/paddlefish.png"),
  "Painted Perch": require("../assets/palia/fish/painted-perch.png"),
  "Palian Betta": require("../assets/palia/fish/palian-betta.png"),
  "Piksii Floatfish": require("../assets/palia/fish/piksii-floatfish.png"),
  "Platinum Chad": require("../assets/palia/fish/platinum-chad.png"),
  "Prism Trout": require("../assets/palia/fish/prism-trout.png"),
  "Radiant Sunfish": require("../assets/palia/fish/radiant-sunfish.png"),
  "Rainbow Trout": require("../assets/palia/fish/rainbow-trout.png"),
  "Red-bellied Piranha": require("../assets/palia/fish/red-bellied-piranha.png"),
  "Ribbontail Ray": require("../assets/palia/fish/ribbontail-ray.png"),
  "Rosy Bitterling": require("../assets/palia/fish/rosy-bitterling.png"),
  "Royal Betta": require("../assets/palia/fish/royal-betta.png"),
  "Sabertoothed Anchovy": require("../assets/palia/fish/sabertoothed-anchovy.png"),
  "Sardine": require("../assets/palia/fish/sardine.png"),
  "Scarlet Koi": require("../assets/palia/fish/scarlet-koi.png"),
  "Shimmerfin": require("../assets/palia/fish/shimmerfin.png"),
  "Sillyfin": require("../assets/palia/fish/sillyfin.png"),
  "Silver Salmon": require("../assets/palia/fish/silver-salmon.png"),
  "Silvery Minnow": require("../assets/palia/fish/silvery-minnow.png"),
  "Smallmouth Bass": require("../assets/palia/fish/smallmouth-bass.png"),
  "Spotted Bullhead": require("../assets/palia/fish/spotted-bullhead.png"),
  "Stalking Catfish": require("../assets/palia/fish/stalking-catfish.png"),
  "Starry Bitterling": require("../assets/palia/fish/starry-bitterling.png"),
  "Stickleback": require("../assets/palia/fish/stickleback.png"),
  "Stonefish": require("../assets/palia/fish/stonefish.png"),
  "Stormray": require("../assets/palia/fish/stormray.png"),
  "Striped Dace": require("../assets/palia/fish/striped-dace.png"),
  "Striped Sturgeon": require("../assets/palia/fish/striped-sturgeon.png"),
  "Swordfin Eel": require("../assets/palia/fish/swordfin-eel.png"),
  "Thundering Eel": require("../assets/palia/fish/thundering-eel.png"),
  "Tinfin": require("../assets/palia/fish/tinfin.png"),
  "Toadstool Floatfish": require("../assets/palia/fish/toadstool-floatfish.png"),
  "Turn Pike": require("../assets/palia/fish/turn-pike.png"),
  "Umbraan Betta": require("../assets/palia/fish/umbraan-betta.png"),
  "Umbran Carp": require("../assets/palia/fish/umbran-carp.png"),
  "Void Ray": require("../assets/palia/fish/void-ray.png"),
  "Willow Lamprey": require("../assets/palia/fish/willow-lamprey.png"),
  "Yellow Perch": require("../assets/palia/fish/yellow-perch.png"),
  "Yellowfin Tuna": require("../assets/palia/fish/yellowfin-tuna.png"),
  };