export const heroBanners: Record<string, any> = {
  "Devil Dinosaur": require("../assets/images/banners/devil-dinosaur-banner.png"),
  "Adam Warlock": require("../assets/images/banners/adam-warlock-banner.png"),
  "Angela": require("../assets/images/banners/angela-banner.png"),
  "Black Cat": require("../assets/images/banners/black-cat-banner.png"),
  "Black Panther": require("../assets/images/banners/black-panther-banner.png"),
  "Black Widow": require("../assets/images/banners/black-widow-banner.png"),
  "Blade": require("../assets/images/banners/blade-banner.png"),
  "Captain America": require("../assets/images/banners/captain-america-banner.png"),
  "Cloak & Dagger": require("../assets/images/banners/cloak-and-dagger-banner.png"),
  "Daredevil": require("../assets/images/banners/daredevil-banner.png"),
  "Deadpool": require("../assets/images/banners/deadpool-banner.png"),
  "Doctor Strange": require("../assets/images/banners/doctor-strange-banner.png"),
  "Elsa Bloodstone": require("../assets/images/banners/elsa-bloodstone-banner.png"),
  "Emma Frost": require("../assets/images/banners/emma-frost-banner.png"),
  "Gambit": require("../assets/images/banners/gambit-banner.png"),
  "Groot": require("../assets/images/banners/groot-banner.png"),
  "Hawkeye": require("../assets/images/banners/hawkeye-banner.png"),
  "Hela": require("../assets/images/banners/hela-banner.png"),
  "Hulk": require("../assets/images/banners/hulk-banner.png"),
  "Human Torch": require("../assets/images/banners/human-torch-banner.png"),
  "Invisible Woman": require("../assets/images/banners/invisible-woman-banner.png"),
  "Iron Fish": require("../assets/images/banners/iron-fist-banner.png"),
  "Iron Man": require("../assets/images/banners/iron-man-banner.png"),
  "Jeff The Landshark": require("../assets/images/banners/jeff-the-landshark-banner.png"),
  "Loki": require("../assets/images/banners/loki-banner.png"),
  "Luna Snow": require("../assets/images/banners/luna-snow-banner.png"),
  "Magik": require("../assets/images/banners/magik-banner.png"),
  "Magneto": require("../assets/images/banners/magneto-banner.png"),
  "Mantis": require("../assets/images/banners/mantis-banner.png"),
  "Mister Fantastic": require("../assets/images/banners/mister-fantastic-banner.png"),
  "Moon Knight": require("../assets/images/banners/moon-knight-banner.png"),
  "Namor": require("../assets/images/banners/namor-banner.png"),
  "Peni Parker": require("../assets/images/banners/peni-parker-banner.png"),
  "Phoenix": require("../assets/images/banners/phoenix-banner.png"),
  "Rocket Raccoon": require("../assets/images/banners/rocket-raccoon-banner.png"),
  "Rogue": require("../assets/images/banners/rogue-banner.png"),
  "Scarlet Witch": require("../assets/images/banners/scarlet-witch-banner.png"),
  "Spider-Man": require("../assets/images/banners/spider-man-banner.png"),
  "Squirrel Girl": require("../assets/images/banners/squirrel-girl-banner.png"),
  "Star-Lord": require("../assets/images/banners/star-lord-banner.png"),
  "Storm": require("../assets/images/banners/storm-banner.png"),
  "The Punisher": require("../assets/images/banners/the-punisher-banner.png"),
  "The Thing": require("../assets/images/banners/the-thing-banner.png"),
  "Thor": require("../assets/images/banners/thor-banner.png"),
  "Ultron": require("../assets/images/banners/ultron-banner.png"),
  "Venom": require("../assets/images/banners/venom-banner.png"),
  "White Fox": require("../assets/images/banners/white-fox-banner.png"),
  "Winter Soldier": require("../assets/images/banners/winter-soldier-banner.png"),
  "Wolverine": require("../assets/images/banners/wolverine-banner.png"),
};